# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: learning/gateway.proto for package 'gateway'

require 'grpc'
require 'learning/gateway_pb'

module Gateway
  module Bot
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gateway.Bot'

      rpc :Setup, SetupRequest, SetupResponse
      rpc :Reply, ReplyRequest, ReplyResponse
      rpc :Replies, ReplyRequests, ReplyResponses
      rpc :Learn, LearnRequest, LearnResponse
    end

    Stub = Service.rpc_stub_class
  end
end
