database:
  endpoint: mysql://myope:yGM7fj2jQQZCui@app-myope.ccfwhx3hbmfs.ap-northeast-1.rds.amazonaws.com/myope?charset=utf8
  host: app-myope.ccfwhx3hbmfs.ap-northeast-1.rds.amazonaws.com
  name: myope
  user: myope
  password: yGM7fj2jQQZCui
default_no_classified_threshold: 0.3
# mysql:
#     host: localhost
#     user: root
#     passwd: my secret password
#     db: write-math
# other:
#     preprocessing_queue:
#         - preprocessing.scale_and_center
#         - preprocessing.dot_reduction
#         - preprocessing.connect_lines
#     use_anonymous: yes
