database:
  endpoint: mysql://root@localhost/donusagi_bot?charset=utf8
  host: localhost
  name: donusagi_bot
  user: root
  password: ""
default_no_classified_threshold: 0.2
# mysql:
#     host: localhost
#     user: root
#     passwd: my secret password
#     db: write-math
# other:
#     preprocessing_queue:
#         - preprocessing.scale_and_center
#         - preprocessing.dot_reduction
#         - preprocessing.connect_lines
#     use_anonymous: yes
