const AllServer = require('./servers/all')
const ChatworkServer = require('./servers/chatwork')
const LineServer = require('./servers/line')
const MicrosoftServer = require('./servers/microsoft')
const SlackServer = require('./servers/slack')

const chatworkServer = new ChatworkServer()
const lineServer = new LineServer()
const microsoftServer = new MicrosoftServer()
const slackServer = new SlackServer()
new AllServer({ lineServer, chatworkServer, microsoftServer, slackServer }).run()