const AllServer = require('./servers/all')
const ChatworkServer = require('./servers/chatwork')
const LineServer = require('./servers/line')
const MicrosoftServer = require('./servers/microsoft')
const AzureServer = require('./servers/azure')
const MyOpeServer = require('./servers/myope')

const chatworkServer = new ChatworkServer()
const lineServer = new LineServer()
const microsoftServer = new MicrosoftServer()
const azureServer = new AzureServer()
const myopeServer = new MyOpeServer()
new AllServer({ lineServer, chatworkServer, microsoftServer, azureServer, myopeServer }).run()