default: &default
  database:
    endpoint: mysql://root@localhost/donusagi_bot?charset=utf8
    host: localhost
    name: donusagi_bot
    user: root
    password: ""

development:
  <<: *default

test:
  <<: *default
  database:
    endpoint: mysql://root@localhost/donusagi_bot_test?charset=utf8
    host: localhost
    name: donusagi_bot_test
    user: root
    password: ""

production:
  <<: *default
  