current:
  algorithm: 8
  bot_id: 25
  testcase:
    version: 0.1.0
    generator: 1
    options:
      src_type: file
      src_path: fixtures/test_messages.csv
      synonym_path: fixtures/synonyms.yml
      dst_type: file
      dst_path: fixtures/test_generated_messages.csv
