export const ADD_QUESTION_TO_QUESTIONS_TREE = "ADD_QUESTION_TO_QUESTIONS_TREE";
export const ADD_ANSWER_TO_ANSWERS_TREE = "ADD_ANSWER_TO_ANSWERS_TREE";
export const ADD_DECISION_BRANCH_TO_ANSWERS_TREE = "ADD_DECISION_BRANCH_TO_ANSWERS_TREE";
export const ADD_DECISION_BRANCH_TO_QUESTIONS_TREE = "ADD_DECISION_BRANCH_TO_ANSWERS_TREE";
export const DELETE_QUESTION_FROM_QUESTIONS_TREE = "DELETE_QUESTION_FROM_QUESTIONS_TREE";
export const DELETE_ANSWER_FROM_ANSWERS_TREE = "DELETE_ANSWER_FROM_ANSWERS_TREE";
export const DELETE_ANSWER_FROM_QUESTIONS_TREE = "DELETE_ANSWER_FROM_QUESTIONS_TREE";
export const DELETE_DECISION_BRANCH_FROM_ANSWERS_TREE = "DELETE_DECISION_BRANCH_FROM_ANSWERS_TREE";
export const DELETE_DECISION_BRANCH_FROM_QUESTIONS_TREE = "DELETE_DECISION_BRANCH_FROM_QUESTOINS_TREE";

export const UPDATE_QUESTION_ANSWER_IN_QUESTIONS_TREE = "UPDATE_QUESTION_ANSWER_IN_QUESTIONS_TREE";

export const UPDATE_QUESTIONS_REPO = "UPDATE_QUESTIONS_REPO";
export const DELETE_QUESTIONS_REPO = "DELETE_QUESTIONS_REPO";
export const ADD_QUESTIONS_REPO = "ADD_QUESTIONS_REPO";

export const UPDATE_ANSWERS_REPO = "UPDATE_ANSWERS_REPO";
export const DELETE_ANSWERS_REPO = "DELETE_ANSWERS_REPO";
export const ADD_ANSWERS_REPO = "ADD_ANSWERS_REPO";

export const UPDATE_DECISION_BRANCHES_REPO = "UPDATE_DECISION_BRANCHES_REPO";
export const DELETE_DECISION_BRANCHES_REPO = "DELETE_DECISION_BRANCHES_REPO";
export const ADD_DECISION_BRANCHES_REPO = "ADD_DECISION_BRANCHES_REPO";

export const ADD_OPENED_QUESTION_IDS = "ADD_OPENED_QUESTION_IDS";
export const REMOVE_OPENED_QUESTION_IDS = "REMOVE_OPENED_QUESTION_IDS";
export const ADD_OPENED_ANSWER_IDS = "ADD_OPENED_ANSWER_IDS";
export const REMOVE_OPENED_ANSWER_IDS = "REMOVE_OPENED_ANSWER_IDS";
export const ADD_OPENED_DECISION_BRANCH_IDS = "ADD_OPENED_DECISION_BRANCH_IDS";
export const REMOVE_OPENED_DECISION_BRANCH_IDS = "REMOVE_OPENED_DECISION_BRANCH_IDS";

export const ON_ADDING_ANSWER = "ON_ADDING_ANSWER";
export const OFF_ADDING_ANSWER = "OFF_ADDING_ANSWER";

export const ON_ADDING_DECISION_BRANCH = "ON_ADDING_DECISION_BRANCH";
export const OFF_ADDING_DECISION_BRANCH = "OFF_ADDING_DECISION_BRANCH";

export const ON_PROCESSING = "ON_PROCESSING";
export const OFF_PROCESSING = "OFF_PROCESSING";

export const SET_ACTIVE_ITEM = "SET_ACTIVE_ITEM";
export const CLEAR_ACTIVE_ITEM = "CLEAR_ACTIVE_ITEM";

export const SET_EDITING_QUESTION_MODEL = "SET_EDITING_QUESTION_MODEL";
export const CLEAR_EDITING_QUESTION_MODEL = "CLEAR_EDITING_QUESTION_MODEL";

export const SET_EDITING_ANSWER_MODEL = "SET_EDITING_ANSWER_MODEL";
export const CLEAR_EDITING_ANSWER_MODEL = "CLEAR_EDITING_ANSWER_MODEL";

export const SET_EDITING_DECISION_BRANCH_MODEL = "SET_EDITING_DECISION_BRANCH_MODEL";
export const CLEAR_EDITING_DECISION_BRANCH_MODEL = "CLEAR_EDITING_DECISION_BRANCH_MODEL";

export const SET_EDITING_DECISION_BRANCH_MODELS = "SET_EDITING_DECISION_BRANCH_MODELS";
export const ADD_EDITING_DECISION_BRANCH_MODELS = "ADD_EDITING_DECISION_BRANCH_MODELS";
export const UPDATE_EDITING_DECISION_BRANCH_MODELS = "UPDATE_EDITING_DECISION_BRANCH_MODELS";
export const DELETE_EDITING_DECISION_BRANCH_MODELS = "DELETE_EDITING_DECISION_BRANCH_MODELS";
export const CLEAR_EDITING_DECISION_BRANCH_MODELS = "CLEAR_EDITING_DECISION_BRANCH_MODELS";
export const ACTIVATE_EDITING_DECISION_BRANCH_MODEL = "ACTIVATE_EDITING_DECISION_BRANCH_MODEL";
export const INACTIVATE_EDITING_DECISION_BRANCH_MODELS = "INACTIVATE_EDITING_DECISION_BRANCH_MODELS";

export const SET_REFERENCE_QUESTION_MODELS = "SET_REFERENCE_QUESTION_MODELS";
export const CLEAR_REFERENCE_QUESTION_MODELS = "CLEAR_REFERENCE_QUESTION_MODELS";
