---
- stat: path=/usr/local/bin/mecab
  register: command

- name: 'install mecab'
  when: not command.stat.exists
  shell: |
    cd /tmp
    wget -O mecab.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE"
    tar xvfz mecab.tar.gz
    cd mecab-0.996
    ./configure --enable-utf8-only
    make
    make check
    sudo make install
    wget -O mecab-ipadic.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM"
    tar zxvf mecab-ipadic.tar.gz
    cd  mecab-ipadic-2.7.0-20070801
    ./configure --with-charset=utf8
    make
