---
- stat: path=/usr/local/bin/mecab
  register: command
- name: 'install mecab'
  when: not command.stat.exists
  shell: |
    cd /tmp
    wget -O mecab.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7cENtOXlicTFaRUE"
    tar xvfz mecab.tar.gz
    cd mecab-0.996
    ./configure --enable-utf8-only
    make
    make check
    sudo make install

- stat: path=/usr/local/lib/mecab/dic/ipadic
  register: d
- name: 'install mecab ipadic'
  when: not d.stat.isdir
  shell: |
    cd /tmp
    wget -O mecab-ipadic.tar.gz "https://drive.google.com/uc?export=download&id=0B4y35FiV1wh7MWVlSDBCSXZMTXM"
    tar zxvf mecab-ipadic.tar.gz
    cd  mecab-ipadic-2.7.0-20070801
    ./configure --with-charset=utf8
    make
    sudo make install

- name: set up dicrc
  template:
    src: dicrc.general
    dest: /usr/local/lib/mecab/dic/ipadic/dicrc

- name: install shell
  copy: src=install-neologd.sh dest=/usr/local/bin owner=root group=root mode=0775

# fatal: destination path 'mecab-ipadic-neologd' already exists and is not an empty directory.
# というエラーが出るがそのまま実行して問題ないため、エラーを無視する
- name: 'install mecab ipadic neologd'
  shell: sudo install-neologd.sh
  ignore_errors: True
