---
- name: install dependencies
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python27
    - mysql57.x86_64
    - mysql57-devel.x86_64

- name: install MySQL
  yum: name=mysql57-server state=latest
  when: 'stage != "production"'

- name: Auto starting MySQL
  service: name=mysqld state=started enabled=yes
  tags: mysqld
  when: 'stage != "production"'

- mysql_db:
    name: '{{ secrets.db_name }}'
    state: present
    login_user: root
    login_password: ''
  when: 'stage != "production"'

- name: set up default encoding
  template:
    src: my.cnf.general
    dest: /etc/my.cnf
  notify: restart mysql
  when: 'stage != "production"'

- name: make symlink for libmysqlclient.so.1020
  file:
    state: link
    dest: /usr/lib64/libmysqlclient.so.1020
    src: /usr/lib64/mysql57/libmysqlclient.so.1020