---
- name: install dependencies
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python27
  when: stage == "development" or stage == "staging"

- name: install MySQL
  yum: name=mysql57-server state=latest
  when: stage == "development" or stage == "staging"

- name: Auto starting MySQL
  service: name=mysqld state=started enabled=yes
  tags: mysqld
  when: stage == "development" or stage == "staging"

- mysql_db:
    name: '{{ secrets.db_name }}'
    state: present
    login_user: root
    login_password: ''
  when: stage == "development" or stage == "staging"

- name: set up default encoding
  template:
    src: my.cnf.general
    dest: /etc/my.cnf
  notify: restart mysql
  when: stage == "development" or stage == "staging"
