---
- name: install dependencies
  yum: name={{ item }} state=installed
  with_items:
    - MySQL-python27

- name: install MySQL
  yum: name=mysql-server state=installed

- name: Auto Running MySQL
  service: name=mysqld state=running enabled=yes
  tags: mysqld

- name: setup password for root
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600

- mysql_user:
    name: 'root'
    host: '{{ item }}'
    state: present
    priv: '*.*:ALL,GRANT'
    password: '{{ passwords.mysql_root }}'
    login_user: root
    login_password: '{{ passwords.mysql_root }}'
    update_password: always
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - localhost.localdomain

- mysql_user:
    name: '{{ secrets.db_user }}'
    host: '{{ item }}'
    state: present
    priv: '*.*:ALL'
    password: '{{ secrets.db_password }}'
    login_user: root
    login_password: '{{ passwords.mysql_root }}'
    update_password: always
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
    - localhost.localdomain

- mysql_db:
    name: '{{ secrets.db_name }}'
    state: present
    login_user: 'root'
    login_password: '{{ passwords.mysql_root }}'
