development:
  adapter: async

test:
  adapter: async

staging:
  adapter: redis
  url: redis://127.0.0.1:6379/1
  channel_prefix: myope_staging

production:
  adapter: redis
  url: redis://localhost:6379/1
