export default {
  botToken: null,
  guestKey: null,
  guestId: null,
  guestUser: null,
  messages: [],
  messagesNextPageExists: false,
  isProcessing: false,
  bot: {},
  isConnected: null,
  notification: '',
  questionAnswers: [],
  isGuestUserRegistrationEnabled: false,
  isGuestUserFormSkippable: false,
}
