export const ADD_MESSAGE = 'ADD_MESSAGE'
export const ADD_MESSAGES = 'ADD_MESSAGES'
export const REPLACE_MESSAGE = 'REPLACE_MESSAGE'

export const SET_MESSAGES_NEXT_PAGE_EXISTS = 'SET_MESSAGE_NEXT_PAGE_EXISTS'

export const SET_IS_PROCESSING = 'SET_IS_PROCESSING'

export const SET_IS_CONNECTED = 'SET_IS_CONNECTED'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'

export const SET_MESSAGE_PAGE = 'SET_MESSAGE_PAGE'
export const SET_MESSAGE_TOTAL_PAGES = 'SET_MESSAGE_TOTAL_PAGES'