---
- hosts: web-servers
  gather_facts: no
  become: yes
  vars:
    ruby_version: 2.4.2
    python_version: 3.5.2
    node_version: 6.9.1
    cert_fqdn: staging.my-ope.net
  vars_files:
    - private.yml
  roles:
    - users
    - base
    - rbenv
    - pyenv
    - ndenv
    - nginx
    - mysql
    - app
    - mecab
    - logrotate
    - { role: slappy, when: stage == 'production' }
