---
- hosts: web-servers
  gather_facts: no
  become: yes
  vars:
    ruby_version: 2.3.4
  vars_files:
    - private.yml
  roles:
    - users
    - base
    - rbenv
    - nginx
    - mysql
    - app
    - mecab
    - logrotate
