---
- hosts: web-servers
  gather_facts: no
  become: yes
  vars:
    ruby_version: 2.4.2
    python_version: 3.5.2
    node_version: 6.9.1
    cert_fqdn: staging.my-ope.net
    myope_api_url:
      production: https://app.my-ope.net
      staging: https://staging.my-ope.net
  vars_files:
    - private.yml
  roles:
    - { role: 'users', tags: 'users' }
    - base
    - rbenv
    - pyenv
    - ndenv
    - nginx
    - mysql
    - app
    - mecab
    - logrotate
    - { role: awslogs, when: stage == 'production' }
