---
- hosts: web-servers
  gather_facts: no
  become: yes
  vars:
    ruby_version: 2.3.4
    python_version: 3.5.2
    cert_fqdn: staging.my-ope.net
  vars_files:
    - private.yml
  roles:
    - users
    - base
    - rbenv
    - pyenv
    - nginx
    - mysql
    - app
    - mecab
    - logrotate
