class Constants:
    COUNT_OF_APPEND_BLANK = 3
    CLASSIFY_FAILED_ANSWER_ID = 0
    ALGORITHM_LOGISTIC_REGRESSION = 0
    ALGORITHM_NAIVE_BAYES = 1
    ALGORITHM_NEURAL_NETWORK = 2
    ALGORITHM_SIMILARITY_CLASSIFICATION = 3
    ALGORITHM_TWO_STEP_SIMILARITY_CLASSIFICATION = 4
    ALGORITHM_WORD2VEC_WMD = 5
    ALGORITHM_HYBRID_CLASSIFICATION = 6
    FEEDBACK_ALGORITHM_NONE = 0
    FEEDBACK_ALGORITHM_ROCCHIO = 1
    DATASOURCE_TYPE_DATABASE = 'database'
    DATASOURCE_TYPE_FILE = 'file'
    RATING_GOOD = 1
    RATING_BAD = 2
