class Constants:
    COUNT_OF_APPEND_BLANK = 3
    CLASSIFY_FAILED_ANSWER_ID = 0
    ALGORITHM_LOGISTIC_REGRESSION = 0
    ALGORITHM_NAIVE_BAYES = 1
    ALGORITHM_NEURAL_NETWORK = 2
    ALGORITHM_SIMILARITY_CLASSIFICATION = 3
    ALGORITHM_TWO_STEP_SIMILARITY_CLASSIFICATION = 4
    DATASOURCE_TYPE_DATABASE = 'database'
    DATASOURCE_TYPE_FILE = 'file'
